#!/bin/sh

fname=/etherdfs/visftp.zip

#git archive -o $fname HEAD
rm -f $fname
#zip $fname Makefile src/*.c src/*.h src/dos/*.c src/dos/*.h src/unix/*.c src/unix/*.h scripts/*
zip -x \*.swp -x \*.o -x \*.obj -r $fname *
